### ISSUE TITLE
[Planejamento] Features site Caso Encerrado

### ISSUE THREAD

**Issue by assuntoencerrado** [assuntoencerrado/documentacao#2]
Por favor coloquem as features que vocês julguem necessário no desenvolvimento do site.

Regras:

1- Indispensável ( no máximo 2)

2- Implementação Futura (no máximo 3)

**Comment by assuntoencerrado** [comment]
- [ ] teste 1
- [ ] teste 2
- [ ] test3

**Comment by YuriBarros** [comment]
Features indispensáveis:
1) Cadastro e opção para recebimento de news letter sobre o desenvolvimento do site;
2) Ter uma área com todas as empresas cadastradas e suas respectivas logos.

De implementação futura:
1) Ranking de empresas amigáveis.
2) Ranking de advogados melhor avaliados.
3) Glossário de termos jurídicos.

**Comment by Juliosiqueiradv** [comment]
Features Indispensáveis:

1- Termo de ciencia do tratamento de dados pessoais (em linguagem acessível);
2- Clube de vantagens.

De implementação futura:

1- Possibilidade das empresas realizarem ofertas de pagamento de dívidas (tipo o que o serasa faz);
2- Evento de premiação das melhores empresas (entrega dos selos);
3- Possibilidade da empresa oferecer em sua página da plataforma, alguns serviços que possui em seu site.(cancelamentos/ contratações de serviços, pagamento de conta, 2ªvia...);
4- IPO.

**Comment by dimascamillo** [comment]
**Features indispensáveis:**

- [x] Cadastro e opção para recebimento de news letter sobre o desenvolvimento do site;
- [x] Ter uma área com todas as empresas cadastradas e suas respectivas logos.
- [x] Termo de ciencia do tratamento de dados pessoais (em linguagem acessível);
- [x] Clube de vantagens.


**De implementação futura:**

- [x] Ranking de empresas amigáveis.
- [x] Ranking de advogados melhor avaliados.
- [x] Glossário de termos jurídicos.
- [x] Possibilidade das empresas realizarem ofertas de pagamento de dívidas (tipo o que o serasa faz);
- [x] Evento de premiação das melhores empresas (entrega dos selos);
- [x] Possibilidade da empresa oferecer em sua página da plataforma, alguns serviços que possui em seu site.(cancelamentos/ contratações de serviços, pagamento de conta, 2ªvia...);
